### ISSUE TITLE
Proposed Example Outline

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-postgresql#51]
I propose we craft a simple example that de-constructs/re-creates the _basic_ GitHub application.
We can _model_ the _basic_ GitHub interface quite easily:

+ [ ] Users
  + [ ] Profile
  + [ ] Repositories 
    + [ ] Collaborators (A _personal_ repository can have zero or more/many contributors_)
    + [ ] Contributions/commits
    + [ ] Issues
      + [ ] Labels (_zero or more_)
      + [ ] Comments
      + [ ] Assignee
  + [ ] Stars
  + [ ] Followers
  + [ ] Following
  + [ ] Orgs (_a user can be a member of zero or more/many organisations_)
+ [ ] Organisations
  + [ ] Members (_an org can have have zero or more/many members_)
  + [ ] Repositories 
    + [ ] Commits
    + [ ] Issues
      + [ ] Comments
      + [ ] Assignee

> **Note**: For now we will deliberately leaving out the "Projects", "Wikis" and Pull Requests for now.
We can _add_ these things in later if desired (_or if readers/learners request them!_). But _for now_, we don't _need_ them in order to explain the _concept_ of relational data.

# Todo

+ [ ] Write "raw" SQL Statements to **`CREATE`** the tables with relationships e.g: [database_setup.sql](https://github.com/nelsonic/time-mvp/blob/747c050032402d040fea4d717aae2ee84e2bac64/server/database_setup.sql)
+ [ ] Create a _sample_ application using SQL statements (no ORM) to allow people to download the code and _run_ it locally to "hack" on it and learn more.

For a _detailed example_ of what I have in mind, see: https://github.com/dwyl/todo-list-javascript-tutorial

Related to #21 & #23 where Jack _requested_ having a simple example.
_Also_ related to #3 as our example _needs_ to have a relational data diagram.

**Comment by nelsonic** [comment]
https://www.postgresql.org/media/img/about/press/slonik_with_black_text_and_tagline.gif
![image](https://user-images.githubusercontent.com/194400/52590572-8b80d300-2e39-11e9-87c5-36298a1428ea.png)

```
<div align="center">
    <a href="https://www.postgresql.org/about/">
        <img src="https://user-images.githubusercontent.com/194400/52590350-fa116100-2e38-11e9-9303-c38819493a4e.png" width="700">
    </a>
</div>
<br />
```

**Comment by nelsonic** [comment]
Stats:
![dbms-ranking](https://user-images.githubusercontent.com/194400/52594416-64c79a00-2e43-11e9-8a61-02af22554802.png)
![stackoverflow-survey-2018-databases](https://user-images.githubusercontent.com/194400/52594468-80cb3b80-2e43-11e9-867a-eeb4eea9a322.png)

**Comment by nelsonic** [comment]
Borrowing the SQL Setup script from:
https://github.com/nelsonic/time-mvp/blob/master/server/database_setup.sql
(_here's one I made earlier ..._)

**Comment by nelsonic** [comment]
DB Setup working on Travis-CI: https://travis-ci.org/dwyl/learn-postgresql/builds/501040678#L501
![image](https://user-images.githubusercontent.com/194400/53693164-85c14200-3d94-11e9-9607-edb7d84afa7b.png)

**Comment by nelsonic** [comment]
Schema Diagram:
![codeface-schema-diagram](https://user-images.githubusercontent.com/194400/55273772-94354780-52c7-11e9-80ed-d515d7f03284.png)

**Comment by nelsonic** [comment]
Export SQL:
![image](https://user-images.githubusercontent.com/194400/55273801-f42bee00-52c7-11e9-9434-5351dd20319e.png)

Select Postgresql:
![image](https://user-images.githubusercontent.com/194400/55273806-09a11800-52c8-11e9-8609-61594a09cf84.png)

![image](https://user-images.githubusercontent.com/194400/55273809-20e00580-52c8-11e9-87b9-6206470af71e.png)

```sql
CREATE TABLE "people" (
	"inserted_at" DATETIME NOT NULL,
	"id" integer(10) NOT NULL UNIQUE,
	"name" VARCHAR(50),
	"username" VARCHAR(50) NOT NULL UNIQUE,
	"company" VARCHAR(50),
	CONSTRAINT people_pk PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "followers" (
	"inserted_at" DATETIME NOT NULL,
	"follower_id" integer(10) NOT NULL,
	"leader_id" integer(10) NOT NULL
) WITH (
  OIDS=FALSE
);



CREATE TABLE "orgs" (
	"inserted_at" DATETIME NOT NULL,
	"id" serial NOT NULL UNIQUE,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	"url" VARCHAR(50) NOT NULL,
	"username" VARCHAR(50) NOT NULL UNIQUE,
	CONSTRAINT orgs_pk PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "members" (
	"inserted_at" DATETIME NOT NULL,
	"person_id" integer NOT NULL,
	"org_id" integer NOT NULL
) WITH (
  OIDS=FALSE
);



CREATE TABLE "repos" (
	"inserted_at" DATETIME NOT NULL,
	"id" serial NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"person_id" integer,
	"org_id" integer,
	CONSTRAINT repos_pk PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "stars" (
	"inserted_at" DATETIME NOT NULL,
	"person_id" integer NOT NULL,
	"repo_id" integer NOT NULL
) WITH (
  OIDS=FALSE
);




ALTER TABLE "followers" ADD CONSTRAINT "followers_fk0" FOREIGN KEY ("follower_id") REFERENCES "people"("id");
ALTER TABLE "followers" ADD CONSTRAINT "followers_fk1" FOREIGN KEY ("leader_id") REFERENCES "people"("id");


ALTER TABLE "members" ADD CONSTRAINT "members_fk0" FOREIGN KEY ("person_id") REFERENCES "people"("id");
ALTER TABLE "members" ADD CONSTRAINT "members_fk1" FOREIGN KEY ("org_id") REFERENCES "orgs"("id");

ALTER TABLE "repos" ADD CONSTRAINT "repos_fk0" FOREIGN KEY ("person_id") REFERENCES "people"("id");
ALTER TABLE "repos" ADD CONSTRAINT "repos_fk1" FOREIGN KEY ("org_id") REFERENCES "orgs"("id");

ALTER TABLE "stars" ADD CONSTRAINT "stars_fk0" FOREIGN KEY ("person_id") REFERENCES "people"("id");
ALTER TABLE "stars" ADD CONSTRAINT "stars_fk1" FOREIGN KEY ("repo_id") REFERENCES "repos"("id");
```

**Comment by nelsonic** [comment]
While the "ALTER TABLE" syntax is best for scalable migrations, I _much_ prefer to have the `CONSTRAINT` contained within the `CREATE TABLE` statement ... 🤔

**Comment by nelsonic** [comment]
running the following command (_on `localhost`_):

```
psql -U postgres -d codeface -a -f schema.sql
```

We can now see the schema in DBeaver's ER (entity relationship) Diagram:

![image](https://user-images.githubusercontent.com/194400/55279339-d7b3a400-530f-11e9-8375-25a0b2dcbd21.png)

Progresso! 🇧🇷

**Comment by nelsonic** [comment]
# Next: 
+ [ ] get some data!

**Comment by nelsonic** [comment]
The Basic App I'm building "CodeFace" is an _ultra-simple_ (read-only) "social network" using GitHub data. I've reached the point where I need to _get_ that data and while attempting to get a Profile using 
https://github.com/nelsonic/github-scraper (_here's one I made earlier..._) I got the following error: https://github.com/nelsonic/github-scraper/issues/91 which blocks progress on this tutorial ... 🚫 

So I'm going to fix https://github.com/nelsonic/github-scraper/issues/91 and BRB!

**Comment by nelsonic** [comment]
I've got the example working for the first 5 tables:
<img width="455" alt="codeface-er-diagram" src="https://user-images.githubusercontent.com/194400/56091357-d18ffc80-5ea5-11e9-93fc-e22cc7a9443b.png">

The next two (`members` and `followers`) are just a repeat of the work done for `stars`,
so should be relatively straightforward.

Given _similarities_ between the `stars`, `members` and `followers` tables,
I'm _considering_ refactoring them into one table **`relationships`**.
I don't know if that will make it more _complex_ or _simplify_ it. 

Any thoughts? 💭

**Comment by nelsonic** [comment]
Refactored it. see #63 ✅

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/56324800-d7b50000-6167-11e9-9e09-c810cb78884c.png)

![what?](https://media.giphy.com/media/xFpT7lMV5Mkqq0E6YM/giphy.gif)
